# Generated by Django 3.0 on 2020-01-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwer',
            new_name='Answer',
        ),
    ]
